### PR TITLE
Don't suppress stderr from rake tasks

### LINKED ISSUE #16: Show migration errors
Hi,

we're using squasher on a fairly old Rails project and in 2009/2010 we wrote much data changing code in our migrations (wouldn't do that now, but we were young and needed the money...). However, many of these migrations fail now, because we changed stuff like acts_as_nested_set and so on.

Squasher fails to execute them, which is ok. But it only stops it execution with exit code 0 instead of showing an error (best thing would be to show the actual error of the migration) and stop with a failure exit code...

### PR DESCRIPTION
**Pull request by lime**
This fixes #16.

The change was added in #14, though I'm not quite sure why. Hiding stderr output should have no effect on what `system` returns.

### CODE REVIEW

File: lib/squasher.rb [hunk 1]
```diff
@@ -18,7 +18,7 @@ def clean
 
   def rake(command, description = nil)
     tell(description) if description
-    system("bundle exec rake #{ command } 2>/dev/null")
+    system("bundle exec rake #{ command }")
```
Comment (lime) [inline lib/squasher.rb]: I doesn't look like Hound is following the same conventions as the current codebase...

**Comment by jalkoby** [comment]
Thanks for the contribution
